name: github-actions(a.m.)
on:
  workflow_dispatch:
 #schedule:
  #- cron: "30 20 * * *"  #5時半に動作
  
env:  #環境変数から文字列(パスワードなど)を取得
  ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
  ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
  CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
  CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
  LINE_NOTIFY: ${{secrets.LINE_NOTIFY}}

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip
          pip install get-chrome-driver --upgrade
          sudo apt-get -y install fonts-ipafont-gothic
          sudo apt-get -y install fonts-ipafont-mincho
          pip install python-dotenv
          pip install selenium
          pip install requests
          pip install pillow
          pip install tweepy
          pip install beautifulsoup4
          python Weather_Bot_am.py
